# Generated by Django 5.1 on 2024-08-24 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='contact_hours_per_week',
        ),
        migrations.AddField(
            model_name='subject',
            name='contact_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.semester'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.semester')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassSubject',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
    ]
