# Generated by Django 5.1 on 2024-08-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_semester_remove_classsubject_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subjects', models.ManyToManyField(to='myapp.subject1')),
            ],
        ),
        migrations.AddField(
            model_name='subject1',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher1'),
        ),
        migrations.CreateModel(
            name='TimetableEntry1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class1')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject1')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher1')),
            ],
        ),
    ]
